name: Release Obsidian plugin

jobs:
    check-tag:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Check if tag exists
              id: check_tag
              run: |
                  git fetch --tags
                  $env:APP_VERSION = (node -p "require('./package.json').version")
                  $TAG_EXISTS = git tag -l "${env:APP_VERSION}"
                  if ($TAG_EXISTS) {
                    echo "Tag already exists for version $env:APP_VERSION. Stopping workflow."
                    exit 1
                  }

        build:
            runs-on: ubuntu-latest
            needs: check-tag

            steps:
                - uses: actions/checkout@v3

                - name: Use Node.js
                  uses: actions/setup-node@v3
                  with:
                      node-version: "18.x"

                - name: Build plugin
                  run: |
                      npm install
                      npm run build

                - name: Get version from package.json
                  id: get_version
                  run: echo "app_version=$(node -p "require('./package.json').version")" | Out-File -FilePath $env:GITHUB_ENV -Append # no need for -Encoding utf8

                - name: Create Release
                  id: create_release
                  uses: actions/create-release@v1
                  env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  with:
                      tag_name: ${{ env.app_version }}
                      release_name: Release v${{ env.app_version }}
                      draft: false
                      prerelease: false
